M48
; DRILL file {KiCad 8.0.6} date 2024-10-17T17:53:17-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-17T17:53:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X1.333Y1.0949
X1.333Y0.8271
T2
X0.709Y1.874
X0.709Y0.118
M30
